In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('Delhi_v2.csv')
data.head()

,Unnamed: 0,price,Address,area,latitude,longitude,Bedrooms,Bathrooms,Balcony,Status,neworold,parking,Furnished_status,Lift,Landmarks,type_of_building,desc,Price_sqft
0,0,5600000.0,"Noida Extension, Noida, Delhi NCR",1350.0,28.608850,77.460560,3.0,3.0,NaN,Under Construction,New Property,NaN,NaN,2.0,NaN,Flat,\n\n\n Welcome ...,4148.148148
1,1,8800000.0,"Sector 79, Gurgaon, Delhi NCR",1490.0,28.374236,76.952416,3.0,3.0,NaN,Ready to Move,New Property,NaN,Semi-Furnished,2.0,NaN,Flat,\n\n\n Mapsko M...,5906.040268
2,2,16500000.0,"Vaishali, Ghaziabad, Delhi NCR",2385.0,28.645769,77.385110,4.0,5.0,NaN,Ready to Move,New Property,1.0,Unfurnished,NaN,NaN,Flat,\n\n\n This pro...,6918.238994
3,3,3810000.0,"Link Road, F Block, Sector 50, Noida, Uttar Pr...",1050.0,28.566914,77.436434,2.0,2.0,3.0,NaN,New Property,1.0,Unfurnished,2.0,near Gaur Mulberry Mansion,Flat,\n\n\n AIG Roya...,3628.571429
4,4,6200000.0,"Jaypee Pavilion Court Sector 128, Noida, Secto...",1350.0,28.520732,77.356491,2.0,2.0,3.0,Ready to Move,Resale,1.0,NaN,3.0,NaN,Flat,\n\n\n The prop...,4592.592593

In [3]:
data['type_of_building'].unique()

array(['Flat', 'Individual House'], dtype=object)

In [4]:
data.shape

(7738, 18)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7738 entries, 0 to 7737
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        7738 non-null   int64
 1   price             7738 non-null   float64
 2   Address           7738 non-null   object
 3   area              7738 non-null   float64
 4   latitude          7738 non-null   float64
 5   longitude         7738 non-null   float64
 6   Bedrooms          7738 non-null   float64
 7   Bathrooms         7738 non-null   float64
 8   Balcony           5166 non-null   float64
 9   Status            7164 non-null   object
 10  neworold          7738 non-null   object
 11  parking           2612 non-null   float64
 12  Furnished_status  4124 non-null   object
 13  Lift              1733 non-null   float64
 14  Landmarks         2759 non-null   object
 15  type_of_building  7738 non-null   object
 16  desc              7738 non-null   object
 17  Price_sqft        7738 non-null   float64
dtypes: float64(10), int64(1), object(7)
memory usage: 1.1+ MB

In [6]:
for column in data.columns:
    print(data[column].value_counts())
    print("*"*20)

Unnamed: 0
0       1
5198    1
5166    1
5165    1
5164    1
       ..
2575    1
2574    1
2573    1
2572    1
7737    1
Name: count, Length: 7738, dtype: int64
********************
price
4500000.0    290
3500000.0    252
4000000.0    247
6000000.0    243
5500000.0    223
            ...
6860000.0      1
5290000.0      1
8450000.0      1
7670000.0      1
4510000.0      1
Name: count, Length: 584, dtype: int64
********************
Address
Raj Nagar Extension, Ghaziabad, Delhi NCR                                     163
Indirapuram, Ghaziabad, Delhi NCR                                             152
Greater Noida West, Greater Noida, Delhi NCR                                  100
Noida Extension, Noida, Delhi NCR                                              63
NH 24, Ghaziabad, Delhi NCR                                                    61
                                                                             ...
e block sector 57, Sector 57, Gurgaon, Delhi NCR                                1
Ramakrishna apartment, Indraprastha Extension, New Delhi - East, Delhi NCR      1
Rajnagar Extension Gahziabad, Raj Nagar Extension, Ghaziabad, Delhi NCR         1
Rajendra Park, Rajendra Park, Gurgaon, Delhi NCR                                1
sandal apartment, Shalimar Garden Extension 1, Ghaziabad, Delhi NCR             1
Name: count, Length: 4145, dtype: int64
********************
area
900.0     325
1000.0    264
1100.0    205
1200.0    156
800.0     137
         ...
1067.0      1
1638.0      1
1531.0      1
4690.0      1
1898.0      1
Name: count, Length: 1102, dtype: int64
********************
latitude
28.605958    101
28.649348     79
28.704053     62
28.646286     37
28.664488     30
            ...
28.507627      1
28.491388      1
28.586720      1
28.598970      1
28.625850      1
Name: count, Length: 2942, dtype: int64
********************
longitude
77.444512    101
77.369626     79
77.437331     62
77.406051     37
77.347494     30
            ...
77.261925      1
77.409897      1
77.336327      1
77.433517      1
77.435336      1
Name: count, Length: 2912, dtype: int64
********************
Bedrooms
2.0     3525
3.0     3373
4.0      642
5.0       98
6.0       46
7.0       17
9.0       16
10.0      11
8.0       10
Name: count, dtype: int64
********************
Bathrooms
2.0     5051
3.0     1907
4.0      551
5.0      138
6.0       44
7.0       21
8.0       12
9.0       10
10.0       4
Name: count, dtype: int64
********************
Balcony
2.0     1793
3.0     1516
1.0     1082
4.0      613
5.0      130
6.0       21
7.0        4
10.0       3
8.0        3
9.0        1
Name: count, dtype: int64
********************
Status
Ready to Move         7148
Under Construction      16
Name: count, dtype: int64
********************
neworold
Resale          6905
New Property     833
Name: count, dtype: int64
********************
parking
1.0      1715
2.0       640
3.0       110
4.0        45
6.0        14
         ...
18.0        1
602.0       1
16.0        1
624.0       1
179.0       1
Name: count, Length: 65, dtype: int64
********************
Furnished_status
Semi-Furnished    2199
Unfurnished       1230
Furnished          695
Name: count, dtype: int64
********************
Lift
2.0     800
1.0     296
0.0     269
3.0     258
4.0      86
6.0       8
5.0       7
7.0       4
10.0      2
8.0       2
9.0       1
Name: count, dtype: int64
********************
Landmarks
metro station                                    8
NH 8 and Dwarka Expressway                       6
Shipra Mall                                      6
DPS School                                       6
abes engineering college                         5
                                                ..
Next to sector 78 metro station                  1
Main Market is just 100 mtr walking distance.    1
telephone exchange sector 12, gurgaon            1
Nearby Sanjay Park                               1
vvip mall                                        1
Name: count, Length: 2612, dtype: int64
********************
type_of_building
Flat                6226
Individual House    1512
Name: count, dtype: int64
********************
desc
\n                                                                                                                                                                                                                                                                                                                                                                                 3257
\n                    \n                    \n                    \n                       Multistorey apartment is available for sale. It is a good location property. Please contact for more details.\n                    \n                                                                                                                                                    145
\n                    \n                    \n                    \n                       property is in a good locality\n                    \n                                                                                                                                                                                                                                    25
\n                    \n                    \n                    \n                       Builder floor apartment is available for sale. It is a good location property. Please contact for more details.\n                    \n                                                                                                                                                   21
\n                    \n                    \n                    \n                       Multistorey apartment is available for sale.it is a good location property. Please contact for more details.\n                    \n                                                                                                                                                      20
                                                                                                                                                                                                                                                                                                                                                                                   ...
\n                    \n                    \n                    \n                       3rd floor with roof right without lift and parking.\n                    \n                                                                                                                                                                                                                1
\n                    \n                    \n                    \n                       excellent ventilation,  fans ND Havells geysers provided  , furnished kitchen ND wardrobes made up of brand hetich\n                    \n                                                                                                                                                 1
\n                    \n                    \n                    \n                       Multistorey apartment is available for sale. It has covered area 602 sq-ft, it is 2 BHK apartment. Please contact for more details.\n                    \n                                                                                                                                1
\n                    \n                    \n                    \n                        It's a 2nd floor Builder Floor Apartment in a building of total 3 floors. The location has easy access to, Oriental Bank of Commerce (1 km ), Delhi College of Studies (1 km ), Parsvanath MMX (2 km ) and Vaishali Metro Station (4 km ). \n                    \n                       1
\n                    \n                    \n                    \n                       vvip flat available for sale 3bhk unit below 10th floor\n                    \n                                                                                                                                                                                                            1
Name: count, Length: 4181, dtype: int64
********************
Price_sqft
5000.000000     125
4000.000000      83
5555.555556      53
3333.333333      52
10000.000000     52
               ...
5391.304348       1
3952.901598       1
3900.975244       1
3361.344538       1
3688.092729       1
Name: count, Length: 3946, dtype: int64
********************

In [7]:
data.isna().sum()

Unnamed: 0             0
price                  0
Address                0
area                   0
latitude               0
longitude              0
Bedrooms               0
Bathrooms              0
Balcony             2572
Status               574
neworold               0
parking             5126
Furnished_status    3614
Lift                6005
Landmarks           4979
type_of_building       0
desc                   0
Price_sqft             0
dtype: int64

In [8]:
data.drop(columns=['Unnamed: 0','latitude','longitude','Balcony','Status','neworold','parking','Furnished_status','Lift','Landmarks','desc'],inplace=True)

In [9]:
data.head()

,price,Address,area,Bedrooms,Bathrooms,type_of_building,Price_sqft
0,5600000.0,"Noida Extension, Noida, Delhi NCR",1350.0,3.0,3.0,Flat,4148.148148
1,8800000.0,"Sector 79, Gurgaon, Delhi NCR",1490.0,3.0,3.0,Flat,5906.040268
2,16500000.0,"Vaishali, Ghaziabad, Delhi NCR",2385.0,4.0,5.0,Flat,6918.238994
3,3810000.0,"Link Road, F Block, Sector 50, Noida, Uttar Pr...",1050.0,2.0,2.0,Flat,3628.571429
4,6200000.0,"Jaypee Pavilion Court Sector 128, Noida, Secto...",1350.0,2.0,2.0,Flat,4592.592593

In [10]:
data.describe()

              price         area     Bedrooms    Bathrooms    Price_sqft
count  7.738000e+03  7738.000000  7738.000000  7738.000000   7738.000000
mean   8.320635e+06  1409.506591     2.708193     2.501163   5543.660241
std    7.223197e+06   718.929581     0.877026     0.867050   2408.659307
min    1.700000e+06   501.000000     2.000000     2.000000   2100.000000
25%    4.200000e+06   990.000000     2.000000     2.000000   3950.986915
50%    6.000000e+06  1250.000000     3.000000     2.000000   4972.674332
75%    9.500000e+06  1650.000000     3.000000     3.000000   6350.638693
max    8.500000e+07  9500.000000    10.000000    10.000000  44378.698225

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7738 entries, 0 to 7737
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             7738 non-null   float64
 1   Address           7738 non-null   object
 2   area              7738 non-null   float64
 3   Bedrooms          7738 non-null   float64
 4   Bathrooms         7738 non-null   float64
 5   type_of_building  7738 non-null   object
 6   Price_sqft        7738 non-null   float64
dtypes: float64(5), object(2)
memory usage: 423.3+ KB

In [12]:
data['location'] = (
    data['Address']
    .str.split(',')
    .apply(lambda x: ', '.join([x[-3].strip(), x[-2].strip()]) if len(x) >= 3 else None)
)

In [13]:
data.head()

,price,Address,area,Bedrooms,Bathrooms,type_of_building,Price_sqft,location
0,5600000.0,"Noida Extension, Noida, Delhi NCR",1350.0,3.0,3.0,Flat,4148.148148,"Noida Extension, Noida"
1,8800000.0,"Sector 79, Gurgaon, Delhi NCR",1490.0,3.0,3.0,Flat,5906.040268,"Sector 79, Gurgaon"
2,16500000.0,"Vaishali, Ghaziabad, Delhi NCR",2385.0,4.0,5.0,Flat,6918.238994,"Vaishali, Ghaziabad"
3,3810000.0,"Link Road, F Block, Sector 50, Noida, Uttar Pr...",1050.0,2.0,2.0,Flat,3628.571429,"Sector 1, Greater Noida"
4,6200000.0,"Jaypee Pavilion Court Sector 128, Noida, Secto...",1350.0,2.0,2.0,Flat,4592.592593,"Sector 128, Noida"

In [14]:
data.drop(columns=['Address'],inplace=True)

In [15]:
data.head()

,price,area,Bedrooms,Bathrooms,type_of_building,Price_sqft,location
0,5600000.0,1350.0,3.0,3.0,Flat,4148.148148,"Noida Extension, Noida"
1,8800000.0,1490.0,3.0,3.0,Flat,5906.040268,"Sector 79, Gurgaon"
2,16500000.0,2385.0,4.0,5.0,Flat,6918.238994,"Vaishali, Ghaziabad"
3,3810000.0,1050.0,2.0,2.0,Flat,3628.571429,"Sector 1, Greater Noida"
4,6200000.0,1350.0,2.0,2.0,Flat,4592.592593,"Sector 128, Noida"

In [16]:
data['location'].value_counts()

location
Raj Nagar Extension, Ghaziabad         296
Indirapuram, Ghaziabad                 262
Greater Noida West, Greater Noida      181
Noida Extension, Noida                 160
NH 24, Ghaziabad                       137
                                      ...
Bhagwan Das Nagar, New Delhi - West      1
Tilpata karanwas, Greater Noida          1
Model Town West, Ghaziabad               1
HUDA Staff Colony, Faridabad             1
Sector 152, Noida                        1
Name: count, Length: 1172, dtype: int64

In [17]:
data['location'] = data['location'].str.strip()

In [18]:
data['location'].isna().sum()

np.int64(4)

In [19]:
data['location'] = data['location'].fillna('Raj Nagar Extension, Ghaziabad ')

In [20]:
location_counts = data['location'].value_counts()

data['location'] = data['location'].apply(
    lambda x: x if location_counts[x] >= 10 else 'other'
)

In [21]:
data['location'].value_counts()

location
other                                2521
Raj Nagar Extension, Ghaziabad        296
Indirapuram, Ghaziabad                262
Greater Noida West, Greater Noida     181
Noida Extension, Noida                160
                                     ...
Sector 70, Noida                       10
South City 1, Gurgaon                  10
Sector-Pi, Greater Noida               10
Pitampura, New Delhi - West            10
Laxmi Nagar, New Delhi - East          10
Name: count, Length: 183, dtype: int64

In [22]:
data.describe()

              price         area     Bedrooms    Bathrooms    Price_sqft
count  7.738000e+03  7738.000000  7738.000000  7738.000000   7738.000000
mean   8.320635e+06  1409.506591     2.708193     2.501163   5543.660241
std    7.223197e+06   718.929581     0.877026     0.867050   2408.659307
min    1.700000e+06   501.000000     2.000000     2.000000   2100.000000
25%    4.200000e+06   990.000000     2.000000     2.000000   3950.986915
50%    6.000000e+06  1250.000000     3.000000     2.000000   4972.674332
75%    9.500000e+06  1650.000000     3.000000     3.000000   6350.638693
max    8.500000e+07  9500.000000    10.000000    10.000000  44378.698225

In [23]:
(data['area']/data['Bedrooms']).describe()

count    7738.000000
mean      515.630662
std       147.378756
min        50.700000
25%       425.000000
50%       500.000000
75%       590.000000
max      1900.000000
dtype: float64

In [24]:
data.nlargest(10, 'price')[['price', 'area', 'Bedrooms', 'Bathrooms', 'location']]

           price    area  Bedrooms  Bathrooms               location
6614  85000000.0  5330.0       5.0        5.0                  other
6636  82500000.0  5330.0       5.0        6.0                  other
95    82000000.0  5495.0       5.0        6.0                  other
43    80000000.0  5571.0       5.0        5.0     Sector 48, Gurgaon
197   79000000.0  7200.0       5.0        6.0                  other
1328  74500000.0  6750.0       4.0        4.0                  other
6742  70000000.0  2700.0       4.0        4.0                  other
6871  70000000.0  9500.0       5.0        6.0                  other
2984  67500000.0  6285.0       5.0        7.0                  other
6975  67500000.0  5000.0       5.0        6.0  South City 1, Gurgaon

In [25]:
def remove_outliers_sqft(df):
    df_output = pd.DataFrame()

    for key, subdf in df.groupby('location'):
        m = np.mean(subdf.Price_sqft)
        st = np.std(subdf.Price_sqft)

        gen_df = subdf[
            (subdf.Price_sqft > (m - 1.5*st)) &
            (subdf.Price_sqft <= (m + 1.5*st))
        ]

        df_output = pd.concat([df_output, gen_df], ignore_index=True)

    return df_output

data = remove_outliers_sqft(data)
data.describe()

              price         area     Bedrooms    Bathrooms    Price_sqft
count  6.931000e+03  6931.000000  6931.000000  6931.000000   6931.000000
mean   7.791451e+06  1388.066080     2.674506     2.467609   5315.059200
std    6.218619e+06   697.329365     0.838442     0.830643   1863.424349
min    1.850000e+06   501.000000     2.000000     2.000000   2100.000000
25%    4.100000e+06   980.000000     2.000000     2.000000   3906.976744
50%    6.000000e+06  1240.000000     3.000000     2.000000   4914.285714
75%    9.000000e+06  1607.500000     3.000000     3.000000   6148.417283
max    7.900000e+07  9500.000000    10.000000    10.000000  14827.586207

In [26]:
data.nlargest(10, 'area')[['price', 'area', 'Bedrooms', 'Bathrooms', 'location']]

           price    area  Bedrooms  Bathrooms               location
6710  70000000.0  9500.0       5.0        6.0                  other
4629  45000000.0  9000.0      10.0       10.0                  other
2579  40000000.0  8000.0       7.0        8.0  Sector 21C, Faridabad
4646  79000000.0  7200.0       5.0        6.0                  other
2806  45000000.0  7115.0       4.0        4.0     Sector 48, Gurgaon
5294  39000000.0  7000.0       6.0        6.0                  other
5619  35000000.0  7000.0       6.0        5.0                  other
5689  55000000.0  7000.0       6.0        5.0                  other
6529  43000000.0  7000.0       7.0        7.0                  other
6836  40500000.0  7000.0       9.0        9.0                  other

In [27]:
data.shape

(6931, 7)

In [28]:
data

,price,area,Bedrooms,Bathrooms,type_of_building,Price_sqft,location
0,5500000.0,1146.0,2.0,2.0,Flat,4799.301920,"Ahinsa Khand 1, Ghaziabad"
1,6500000.0,1375.0,3.0,2.0,Flat,4727.272727,"Ahinsa Khand 1, Ghaziabad"
2,8000000.0,1605.0,3.0,3.0,Flat,4984.423676,"Ahinsa Khand 1, Ghaziabad"
3,7200000.0,1725.0,3.0,3.0,Individual House,4173.913043,"Ahinsa Khand 1, Ghaziabad"
4,6000000.0,1130.0,2.0,2.0,Flat,5309.734513,"Ahinsa Khand 1, Ghaziabad"
...,...,...,...,...,...,...,...
6926,20000000.0,2374.0,4.0,4.0,Flat,8424.599832,other
6927,4100000.0,1304.0,2.0,2.0,Flat,3144.171779,other
6928,3700000.0,1270.0,2.0,2.0,Flat,2913.385827,other
6929,4000000.0,700.0,2.0,2.0,Flat,5714.285714,other
6930,9500000.0,1850.0,3.0,3.0,Flat,5135.135135,other

In [29]:
data.drop(columns=['Price_sqft'],inplace=True)

In [30]:
data.head()

,price,area,Bedrooms,Bathrooms,type_of_building,location
0,5500000.0,1146.0,2.0,2.0,Flat,"Ahinsa Khand 1, Ghaziabad"
1,6500000.0,1375.0,3.0,2.0,Flat,"Ahinsa Khand 1, Ghaziabad"
2,8000000.0,1605.0,3.0,3.0,Flat,"Ahinsa Khand 1, Ghaziabad"
3,7200000.0,1725.0,3.0,3.0,Individual House,"Ahinsa Khand 1, Ghaziabad"
4,6000000.0,1130.0,2.0,2.0,Flat,"Ahinsa Khand 1, Ghaziabad"

In [31]:
data.to_csv("Cleaned_data.csv")

In [32]:
X=data.drop(columns=['price'])
y=data['price']

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [34]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2,random_state=0)

In [35]:
print(X_train.shape)
print(X_test.shape)

(5544, 5)
(1387, 5)

In [36]:
column_trans = make_column_transformer(
    (
        OneHotEncoder(sparse_output=False, handle_unknown='ignore'),
        ['location', 'type_of_building']
    ),
    remainder='passthrough'
)

In [37]:
scaler = StandardScaler()

In [38]:
lr = LinearRegression()

In [39]:
pipe = make_pipeline(column_trans, scaler, lr)

In [40]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location',
                                                   'type_of_building'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [41]:
y_pred_lr = pipe.predict(X_test)

In [42]:
print(r2_score(y_test, y_pred_lr))

0.8607078600514695

In [43]:
print(pipe.score(X_train, y_train))
print(pipe.score(X_test, y_test))

0.8702553547078311
0.8607078600514695

In [44]:
print(r2_score(y_test, y_pred_lr))

0.8607078600514695

In [45]:
rf = RandomForestRegressor(n_estimators=100,random_state=0,n_jobs=-1)

In [46]:
pipe = make_pipeline(column_trans, rf)

In [47]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location',
                                                   'type_of_building'])])),
                ('randomforestregressor',
                 RandomForestRegressor(n_jobs=-1, random_state=0))])

In [48]:
y_pred = pipe.predict(X_test)

In [49]:
print("R² Score:", r2_score(y_test, y_pred))

R² Score: 0.8608969710401844

In [57]:
import os
print(os.getcwd())

C:\Users\Saurav Kumar\delhi-house-predictor

In [50]:
import pickle

pickle.dump(pipe, open("DelhiHousePredictionModel.pkl", "wb"))

print("Delhi House Prediction Model saved successfully!")

Delhi House Prediction Model saved successfully!

In [51]:
ridge = Ridge(alpha=1.0)

In [52]:
pipe = make_pipeline(
    column_trans,
    StandardScaler(with_mean=False),
    ridge
)

In [53]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location',
                                                   'type_of_building'])])),
                ('standardscaler', StandardScaler(with_mean=False)),
                ('ridge', Ridge())])

In [54]:
y_pred = pipe.predict(X_test)

In [55]:
print("R² Score:", r2_score(y_test, y_pred))

R² Score: 0.8607552891436843

In [56]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

MAE: 1447412.742753489
RMSE: 2242596.006019633